import React from "react";
import { StyleSheet } from "react-native";

const size = StyleSheet.create({
  title: {
    color: "#24372B",
    fontWeight: 800,
    fontSize: 25,
    marginLeft: 8,
  },
  reservationstitle: {
    color: "#24372B",
    fontWeight: 800,
    fontSize: 25,
    marginLeft: 200,
  },
  viewmorecta: {
    color: "#24372B",
    fontSize: 15,
    marginRight: 8,
  },
  seemorecta: {
    color: "#EBF2EE",
    fontSize: 14,
    fontWeight: 500,
    marginRight: 5,
  },
  booknowcta: {
    color: "#EBF2EE",
    fontSize: 14,
    fontWeight: 500,
    marginRight: 10,
    marginLeft: 250,
    marginTop: -60,
  },
  booknowarrow: {
    marginTop: -60,
  },
  seemenucta: {
    color: "#EBF2EE",
    fontSize: 14,
    fontWeight: 500,
  },
  butterchickentitle: {
    color: "#ADCCB9",
    marginBottom: 5,
    fontSize: 20,
    fontWeight: 500,
  },
  butterchickendescription: {
    fontSize: 14,
    color: "#EBF2EE",
    marginBottom: 20,
  },
  pricetag: {
    color: "#24372B",
    fontSize: 15,
  },
  pricetagcontainer: {
    backgroundColor: "#ADCCB9",
    width: 69,
    height: 33,
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  homestar: {
    color: "#FCFF78",
    fontSize: 20,
  },
  rating: {
    color: "#EBF2EE",
    fontSize: 15,
    marginLeft: 5,
  },
  tikkatitle: {
    color: "#ADCCB9",
    marginBottom: 5,
    fontSize: 20,
    fontWeight: 500,
  },
  tikkadescription: {
    fontSize: 14,
    color: "#EBF2EE",
    marginBottom: 20,
    marginLeft: 1,
  },
  thairedtitle: {
    color: "#ADCCB9",
    marginBottom: 5,
    fontSize: 20,
    fontWeight: 500,
  },
  thaireddescription: {
    fontSize: 14,
    color: "#EBF2EE",
    marginBottom: 20,
    marginLeft: 1,
  },
  tofuspinachtitle: {
    color: "#ADCCB9",
    marginBottom: 5,
    fontSize: 20,
    fontWeight: 500,
  },
  tofuspinachdescription: {
    fontSize: 14,
    color: "#EBF2EE",
    marginBottom: 20,
    marginLeft: 1,
  },
  fortext: {
    color: "#365240",
    fontSize: 18,
    fontWeight: 700,
  },
  promonumbertext: {
    color: "#365240",
    fontSize: 18,
    fontWeight: 800,
  },
  deliciousindianplatetext: {
    color: "#365240",
    fontSize: 18,
    fontWeight: 700,
    marginLeft: 35,
  },
  dessertsection_h1: {
    color: "#EBF2EE",
    fontSize: 25,
    fontWeight: 700,
    marginBottom: 5,
  },
  dessertsection_h2: {
    color: "#EBF2EE",
    fontSize: 15,
    fontWeight: 700,
    marginBottom: 15,
  },
  reservationstitletext: {
    color: "#365240",
    fontSize: 18,
    fontWeight: 700,
    marginLeft: 20,
    marginTop: "-42%",
  },
  reservationsdescriptiontext: {
    color: "#ADCCB9",
    fontWeight: 600,
    fontSize: 15,
    position: "absolute",
    zIndex: 3,
    marginLeft: 20,
    marginTop: -120,
  },
  menufilteritemboxactive: {
    width: 80,
    height: 40,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EBF2EE",
    borderColor: "#24372B",
    borderWidth: 1.5,
  },
  menufilteritemtextactive: {
    fontSize: 15,
    color: "#24372B",
  },
  vegetarianbox: {
    width: 93,
    height: 40,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#24372B",
    borderColor: "#24372B",
    borderWidth: 1.5,
    marginLeft: 5,
  },
  menufilteritemtext: {
    fontSize: 15,
    color: "#EBF2EE",
  },
  veganbox: {
    width: 80,
    height: 40,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#24372B",
    borderColor: "#24372B",
    borderWidth: 1.5,
    marginLeft: 5,
  },
  talibox: {
    width: 70,
    height: 40,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#24372B",
    borderColor: "#24372B",
    borderWidth: 1.5,
    marginLeft: 5,
    marginRight: 8,
  },
  drinksbox: {
    width: 70,
    height: 40,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#24372B",
    borderColor: "#24372B",
    borderWidth: 1.5,
    marginLeft: 5,
    marginRight: 8,
  },
  dessertsbox: {
    width: 70,
    height: 40,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#24372B",
    borderColor: "#24372B",
    borderWidth: 1.5,
    marginLeft: 5,
    marginRight: 8,
  },
  menusectiontitle: {
    fontSize: 20,
    color: "#24372B",
    marginBottom: 5,
  },
  menusectiondescription: {
    fontSize: 14,
    color: "#61846E",
    marginBottom: 18,
  },
  menupricetext: {
    color: "#24372B",
  },
  menustar: {
    fontSize: 18,
    color: "#FFAC0C",
    marginRight: 5,
  },
  menuratingtext: {
    fontSize: 11,
  },
  mangobowltitle: {
    color: "#24372B",
    fontSize: 25,
    fontWeight: 500,
    marginTop: 10,
    marginBottom: 5,
  },
  mangobowldescription: {
    color: "#61846E",
    fontSize: 15,
    marginBottom: 10,
  },
  itemstar: {
    color: "#FFAC0C",
    fontSize: 20,
    marginRight: 5,
  },
  itemrating: {
    color: "#24372B",
    fontSize: 15,
  },
  extrastitle: {
    color: "#24372B",
    marginBottom: 10,
    fontSize: 25,
    fontWeight: 500,
    marginTop: 35,
  },
  samosa: {
    fontSize: 12,
    color: "#24372B",
  },
});

export default size;
